"""change_video_id_to_text

Revision ID: 8a2cf9a2da93
Revises: e63bfe05ce7e
Create Date: 2025-05-22 14:17:15.112841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2cf9a2da93'
down_revision: Union[str, None] = 'e63bfe05ce7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('video_s3_key', sa.TEXT(), nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE', 'PUBLIC', 'UNLISTED', name='videovisibility'), nullable=False),
    sa.Column('is_processing', sa.Enum('COMPLETED', 'FAILED', 'IN_PROGRESS', name='processingstatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.cognito_sub'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
